version: "3.9"

services:
  freellmapi:
    build: .
    container_name: freellmapi
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ENCRYPTION_KEY=a1cc3501b79487748e1fdbfca0e6ced8dbaaf3d186553ea91448bc4023e8a285
      - API_KEY=your_api_key_here
    expose:
      - "3001"
    
    labels:
      - "traefik.enable=true"

      # Basic Auth
      - "traefik.http.middlewares.freellmapi-auth.basicauth.users=admin:$$2y$$05$$H6uskkkW9u9y9F8V0cP8X.7m2F1vd2o9hMT1H9kD114F8CbnZ4Ei6"

      # Attach auth to ALL routers of this container
      - "traefik.http.routers.*.middlewares=freellmapi-auth@docker"

      # Service port
      - "traefik.http.services.freellmapi.loadbalancer.server.port=3001"

 
   


    restart: unless-stopped
