version: "3.9"

services:
  freellmapi:
    build: .
    container_name: freellmapi
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ENCRYPTION_KEY=a1cc3501b79487748e1fdbfca0e6ced8dbaaf3d186553ea91448bc4023e8a285
      - API_KEY=your_api_key_here
    expose:
      - "3001"
    
labels:
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`subdomain.mydomain.com`)"
      - "traefik.http.routers.myapp.middlewares=auth-middleware"
      - "traefik.http.middlewares.auth-middleware.basicauth.users=admin:$$2y$$10$$g/3wNcGw/SLJ0i3PMFnKEeA1vns9g3iFK9ffQGXc4yv0kn0553AZC"


    restart: unless-stopped
